name: Continuous Integration
on: [pull_request, workflow_dispatch]

permissions: read-all

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-and-lint-station-ui:
    uses: ./.github/workflows/test-station-ui.yml
    secrets: inherit
