name: Test Station UI

on: [workflow_call, workflow_dispatch]

permissions:
  contents: read

env:
  MIX_ENV: test
  ELIXIR_VERSION: 1.15.7
  OTP_VERSION: 26.1.2

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Elixir app for CI
        uses: ./.github/actions/setup-sui-for-ci
      - run: mix compile --force --warnings-as-errors
  check_formatted:
    name: Check Formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Elixir app for CI
        uses: ./.github/actions/setup-sui-for-ci
      - run: mix deps.compile
      - run: mix format --check-formatted

  credo:
    name: Credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Elixir app for CI
        uses: ./.github/actions/setup-sui-for-ci
      - run: mix credo

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Elixir app for CI
        uses: ./.github/actions/setup-sui-for-ci
      - run: mix test
